version: '3'

volumes:
  postgres_data: {}
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DATABASE=postgres
  clients:
    build: clients_service/.
    container_name: client_service
    command: uvicorn --host 0.0.0.0 --port 8000 clients_api:app --reload
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      - db
  transactions:
    build: transactions_service/.
    container_name: transaction_service
    command: uvicorn --host 0.0.0.0 --port 8001 transactions_api:app --reload
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - DB_HOST=db
    depends_on:
      - clients

