version: '3'

volumes:
  postgres_data: {}
services:
  clients:
    build: clients_service/.
    container_name: client_service
    command: uvicorn --host 0.0.0.0 --port 8000 clients_api:app --reload
    ports:
      - "8000:8000"
    restart: on-failure
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      - db
  transactions:
    build: transactions_service/.
    container_name: transaction_service
    command: uvicorn --host 0.0.0.0 --port 8001 transactions_api:app --reload
    ports:
      - "8001:8001"
    restart: on-failure
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    env_file:
      - .env
